"""add document ingestion metadata

Revision ID: 4fd9fe029eb4
Revises: b14b25f0c083
Create Date: 2026-07-02 10:43:24.490846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fd9fe029eb4'
down_revision: Union[str, Sequence[str], None] = 'b14b25f0c083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.add_column('documents', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('documents', sa.Column('indexed_at', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('failure_reason', sa.String(length=2048), nullable=True))
    op.add_column('documents', sa.Column('ingestion_version', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('qdrant_points_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('duckdb_tables_count', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_column('documents', 'duckdb_tables_count')
    op.drop_column('documents', 'qdrant_points_count')
    op.drop_column('documents', 'ingestion_version')
    op.drop_column('documents', 'failure_reason')
    op.drop_column('documents', 'indexed_at')
    op.drop_column('documents', 'is_active')
    op.drop_column('documents', 'content_hash')
    # ### end Alembic commands ###
