"""add s3 object key to documents

Revision ID: b14b25f0c083
Revises: 165631c83cea
Create Date: 2026-06-24 14:08:37.095380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b14b25f0c083'
down_revision: Union[str, Sequence[str], None] = '165631c83cea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('s3_object_key', sa.String(length=1024), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 's3_object_key')
    # ### end Alembic commands ###
