"""add companies and company email domains

Revision ID: ea969c869ace
Revises: 4fd9fe029eb4
Create Date: 2026-07-06 13:47:55.441051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea969c869ace'
down_revision: Union[str, Sequence[str], None] = '4fd9fe029eb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_email_domains',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_email_domains_company_id'), 'company_email_domains', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_email_domains_domain'), 'company_email_domains', ['domain'], unique=True)
    op.add_column('workspaces', sa.Column('company_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_workspaces_company_id'), 'workspaces', ['company_id'], unique=False)
    op.create_foreign_key(None, 'workspaces', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.drop_index(op.f('ix_workspaces_company_id'), table_name='workspaces')
    op.drop_column('workspaces', 'company_id')
    op.drop_index(op.f('ix_company_email_domains_domain'), table_name='company_email_domains')
    op.drop_index(op.f('ix_company_email_domains_company_id'), table_name='company_email_domains')
    op.drop_table('company_email_domains')
    op.drop_table('companies')
    # ### end Alembic commands ###
